services:
  php:
    build:
      context: ./docker/php-fpm
      dockerfile: Dockerfile
    container_name: php
    volumes:
      - ./php.ini:/usr/local/etc/php/php.ini
      - ./app:/var/www/html
    ports:
      - "9000:9000"
    networks:
      - app-network
    restart: always
  nginx:
    image: nginx:1.21.3
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./app:/var/www/html
    ports:
      - "80:80"
    networks:
      - app-network
    depends_on:
      - php
  mysql:
    image: mysql:9
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tracker
      MYSQL_USER: tracker
      MYSQL_PASSWORD: deploy
    volumes:
      - mysql-data:/var/lib/mysql
      - ./mysql.cnf:/etc/mysql/conf.d/mysql.cnf
    ports:
      - "3306:3306"
    networks:
      - app-network
    restart: always
  memcached:
    image: memcached:1.6.9
    container_name: memcached
    ports:
      - "11211:11211"
    networks:
      - app-network
    restart: always
  rabbitmq:
    image: rabbitmq:3.9.7-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
volumes:
  mysql-data: